# production
services:
  app:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "8080:8080"
    environment:
      DD_AGENT_HOST: ${DD_AGENT_HOST}
      DD_ENV: ${DD_ENV}
      DD_SERVICE: ${DD_SERVICE}
      DD_VERSION: ${DD_VERSION}
    depends_on:
      - db

  db:
    image: postgres:14
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
