services:
  app:
    env_file:
      - .env.dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: todo-app:latest # Image name
    container_name: todo-app
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: postgres:14
    container_name: todo-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data # postgres official directory

volumes:
  db-data:
