name: Deploy React App to S3

on:
  push:
    branches:
      - main  # `main`ブランチにpushしたらこのアクションが実行される

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest  # GitHub Actionsの実行環境（最新のUbuntu）

    defaults:
      run:
        working-directory: frontend  # Reactアプリのルートディレクトリ

    steps:
      - name: Checkout source
        uses: actions/checkout@v4  # リポジトリからコードをクローン

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'  # 使用するNode.jsのバージョン

      - name: Install dependencies
        run: npm install  # 必要な依存パッケージをインストール

      - name: Build React app
        run: npm run build  # Reactアプリをビルド

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1  # 東京リージョン

      - name: Deploy to S3
        run: aws s3 sync dist/ s3://todo-app-front/ --delete
