name: Generate JaCoCo Report on PR

on:
  pull_request:
    branches:
      - main

jobs:
  jacoco:
    name: Run Tests and Report Coverage
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Create application.properties
        run: echo "${{ secrets.APP_PROPERTIES_FILE }}" > src/main/resources/application.properties
        working-directory: backend

      - name: Run tests
        run: ./gradlew test

      - name: Generate Jacoco Report in PR
        uses: madrapps/jacoco-report@v1.7.2
        with:
          paths: ${{ github.workspace }}/backend/build/customJacocoReportDir/test/jacocoTestReport.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          skip-if-no-changes: true
